networks:
    default:
        name: llm-rag-network
        external: true
services:
    llm-rag-cli:
        image: llm-rag-cli
        container_name: llm-rag-cli
        ports:
            - 8501:8501  # Streamlit default port
        volumes:
            - ../secrets:/secrets
            - ../padoc:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
            OPENAI_API_KEY: $OPENAI_API_KEY
        depends_on:
            - chromadb
    chromadb:
        image: chromadb/chroma:latest
        container_name: llm-rag-chromadb-pharma
        ports:
            - 8000:8000
        volumes:
            - ./docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE
            - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"] # This is not recommended for production environments.